model:
    name:           PTZ Reconfiguration

    res_min_ideal:          2.8
    res_min_acceptable:     0.7
    blur_max_acceptable:    215.0538
    angle_max_ideal:        0.70
    angle_max_acceptable:   0.98

    cameras:
        - name:         C1
          sprites:      [cameras/prosilicaec1350.yaml, lenses/computarh10z1218mp.yaml]
          A:            4.4765
          f:            12.253
          s:            0.00465
          o:            [763.00966, 579.1370]
          dim:          [1360, 1024]
          zS:           1252.15
          mount:        ServoArm
          pose:
              T:            [0, 62.5, 45]
              R:            [-90, 0, 180]
              Rformat:      euler-zyx-deg
    scene:
        # floor
        - name:         FloorA
          vertices:
            - [-800, -600, 0]
            - [800, -600, 0]
            - [800, 600, 0]
        - name:         FloorB
          vertices:
            - [800, 600, 0]
            - [-800, 600, 0]
            - [-800, -600, 0]
        - name:         ServoArm
          robot:        robots/pan_tilt_sevos.yaml
          config:       [45.72, 45.72, 0]
